import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import '../globals.css';

const openSans = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Awesome Node App',
  description: 'Generated by Create Awesome Node App',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={openSans.className}>{children}</body>
    </html>
  );
}
